#端口号
server:
  port: 8888

spring:
  application:
    name: springboot-shutdown #服务名

  redis:
    database: 0 #Redis数据库索引（默认为0）
    timeout: 5000ms # 连接超时时间（毫秒）
    host: localhost
    port: 6379
    password:  # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池中的最大连接
        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8  # 连接池中的最大空闲连接
        min-idle: 0  # 连接池中的最小空闲连接
